services:

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: demo_project
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - micro-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    #build: ./user-service //image locally build
    image: shagunbawaniya19/user-service:1.0
    container_name: user-service-container
    env_file:
      - ./user-service/.env
    ports:
      - "3000:3000"
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - micro-net

  product-service:
    image: shagunbawaniya19/product-service:1.0
    container_name: product-service-container
    env_file:
      - ./product-service/.env
    ports:
      - "3001:3001"
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - micro-net

  profile-service:
    image: shagunbawaniya19/profile-service:1.0
    container_name: profile-service-container
    env_file:
      - ./profile-service/.env
    ports:
      - "3002:3002"
    depends_on:
      - user-service
      - product-service
    networks:
      - micro-net

  api-gateway:
    image: shagunbawaniya19/api-gateway:1.0
    container_name: api-gateway-container
    env_file:
      - ./api-gateway/.env
    ports:
      - "5001:5001"
    depends_on:
      - user-service
      - product-service
      - profile-service
    networks:
      - micro-net

networks:
  micro-net:

volumes:
  postgres-data: